diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Rahym
user.email=rahym.syd11@gmail.com
http.postbuffer=524288000
http.version=HTTP/1.1
core.compression=0
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.menin-obam.url=https://github.com/rahymseyidov/menin-obam.git
remote.menin-obam.fetch=+refs/heads/*:refs/remotes/menin-obam/*
remote.origin.url=git@github.com:rahymseyidov/menin-obam.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
